### ISSUE TITLE
Domain setup and basic access

### ISSUE THREAD

**Issue by BendaJambit** [jambit/attendance-list-backend#1]
### Description

This serves as the first epic.

### Tasks
- [ ] Create Entities based on ERD in Domain
- [ ] Create DbContexts and Migrations in Infrastructure
- [ ] Implement Repositories for each Aggregate 

### Acceptance Criteria

- It is possible to create admin Accounts over public endpoint (will be changed in the future).
- Admins can create Users with 'Team' role.
- Admins can create a Group for a User with 'Team' role.
- Admins can create a Child.
- Admins can create Group Designation.
- Admin can add Child to Group.
